project_name: tier
release:
  prerelease: auto # don't publish release with -rc1,-pre, etc suffixes
before:
  hooks:
    - go mod tidy
    # - ./script/completions
builds:
  - id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/tier
    binary: "tier"
    ldflags:
      - -X tier.run/version.Long={{.Env.VERSION_LONG}} -X tier.run/version.Short={{.Env.VERSION_SHORT}} -X tier.run/version.GitCommit={{.Env.VERSION_GIT_HASH}}
  - id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    main: ./cmd/tier
    binary: "tier"
    ldflags:
      - -X tier.run/version.Long={{.Env.VERSION_LONG}} -X tier.run/version.Short={{.Env.VERSION_SHORT}} -X tier.run/version.GitCommit={{.Env.VERSION_GIT_HASH}}
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/tier
    binary: "tier"   
    ldflags:
      - -X tier.run/version.Long={{.Env.VERSION_LONG}} -X tier.run/version.Short={{.Env.VERSION_SHORT}} -X tier.run/version.GitCommit={{.Env.VERSION_GIT_HASH}}
dockers:
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "tierrun/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "tierrun/{{ .ProjectName }}:latest-arm64"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    dockerfile: Dockerfile.goreleaser
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "tierrun/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "tierrun/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    dockerfile: Dockerfile.goreleaser
nfpms:
  - maintainer: Tier
    description: The Tier CLI
    homepage: https://github.com/tierrun/tier
    license: BSD-3-Clause
    # contents:
    #   - src: ./completions/tier.bash
    #     dst: /etc/bash_completion.d/tier
    #   - src: ./completions/tier.fish
    #     dst: /usr/share/fish/completions/tier.fish
    #   - src: ./completions/tier.zsh
    #     dst: /usr/local/share/zsh/site-functions/_tier
    formats:
    - deb
    - rpm
# scoop:
#   bucket:
#     owner: tier
#     name: scoop-bucket
#   homepage: "https://tier.run/docs"
#   description: "The Tier CLI"
#   license: BSD-3-Clause
brews:
  - homepage: "https://tier.run/"
    description: "The Tier CLI"
    name: "tier"
    license: BSD-3-Clause
    tap: 
      owner: tierrun
      name: homebrew-tap
    folder: Formula
    test: |
         system "#{bin}/tier version --homebrew"
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    rlcp: true

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
