// Copyright (c) 2022 Tailscale Inc & AUTHORS All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package tier

// Clone makes a deep copy of Tier.
// The result aliases no memory with the original.
func (src *Tier) Clone() *Tier {
	if src == nil {
		return nil
	}
	dst := new(Tier)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _TierCloneNeedsRegeneration = Tier(struct {
	Upto  int
	Price int
	Base  int
}{})

// Clone makes a deep copy of Feature.
// The result aliases no memory with the original.
func (src *Feature) Clone() *Feature {
	if src == nil {
		return nil
	}
	dst := new(Feature)
	*dst = *src
	dst.Tiers = append(src.Tiers[:0:0], src.Tiers...)
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _FeatureCloneNeedsRegeneration = Feature(struct {
	ProviderID string
	Plan       string
	PlanTitle  string
	Name       string
	Title      string
	Interval   string
	Currency   string
	Base       int
	Mode       string
	Aggregate  string
	Tiers      []Tier
	ReportID   string
}{})
